import type { Metadata } from "next"
import { Anek_Tamil } from "next/font/google"
import "./globals.css"

const anek_tamil = Anek_Tamil({ subsets: ["latin"], weight: ["400", "500"] })

export const metadata: Metadata = {
	// title: "Create Next App",
	// description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body className={`py-[3.125rem] px-[0.9375rem] ${anek_tamil.className}`}>{children}</body>
		</html>
	)
}
